# Generated by Django 3.2.6 on 2023-02-15 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230215_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
