version: "3.9"

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_DEFAULT_VHOST=/
    ports:
      - 5672:5672
      - 15672:15672
  celeryworker:
    container_name: celeryworker
    restart: always
    build: .
    env_file:
      - ./.env.dev
    command: celery -A core worker --pool=prefork -l info
    depends_on:
      - rabbitmq

  celeryscheduler:
    container_name: celeryscheduler
    restart: always
    build: .
    env_file:
      - ./.env.dev
    command: celery -A core beat -l info
    depends_on:
      - celeryworker

  celeryflower:
    container_name: celeryflower
    restart: always
    build: .
    env_file:
      - ./.env.dev
    command: celery -A core flower -l info
    ports:
      - 5555:5555
    depends_on:
      - celeryworker
      - celeryscheduler

volumes:
  postgres_data:
