version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - db
    restart: always
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    restart: always
  redis:
    image: redis
    ports:
      - 6379:6379
    env_file:
      - ./.env
    restart: always
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - 80:80
    depends_on:
      - web
    restart: always
  celeryworker:
    container_name: celeryworker
    restart: always
    build: .
    env_file:
      - ./.env
    command: celery -A core worker --pool=prefork -l info
    depends_on:
      - redis
  celeryscheduler:
    container_name: celeryscheduler
    build: .
    env_file:
      - ./.env
    command: celery -A core beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    depends_on:
      - celeryworker
    restart: always
  celeryflower:
    container_name: celeryflower
    build: .
    env_file:
      - ./.env
    command: celery -A core flower -l info
    expose:
      - 5555
    ports:
      - 5555:5555
    depends_on:
      - celeryworker
      - celeryscheduler
    restart: always
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    restart: always
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    restart: always
  postgres-exporter:
    image: prometheuscommunity/postgres-exporter
    ports:
      - 9187:9187
    environment:
      DATA_SOURCE_NAME: "postgresql://hello_django:hello_django@db:5432/hello_django_dev?sslmode=disable"
    links:
      - db
      - prometheus
    restart: always
  redis-exporter:
    image: oliver006/redis_exporter
    ports:
      - 9121:9121
    environment:
      REDIS_ADDR: "redis:6379"
      REDIS_USER: null
      REDIS_PASSWORD: my_master_password
    links:
      - redis
      - prometheus
    restart: always
volumes:
  postgres_data:
  static_volume:
  media_volume:
