global:
  scrape_interval: 15s
  evaluation_interval: 15s
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: postgres-exporter
    static_configs:
      - targets: ["postgres-exporter:9187"]
  - job_name: celery-flower
    static_configs:
      - targets: ["celeryflower:5555"]
  - job_name: redis-exporter
    static_configs:
      - targets: ["redis-exporter:9121"]
