# Generated by Django 3.2.6 on 2023-02-15 11:52

from django.db import migrations
import shortuuidfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='idx',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, db_index=True, editable=False, max_length=22, unique=True),
        ),
    ]
