# Generated by Django 4.1.7 on 2023-05-20 22:05

from django.db import migrations, models
import shortuuidfield.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Config",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "idx",
                    shortuuidfield.fields.ShortUUIDField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        max_length=22,
                        unique=True,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                ("is_obsolete", models.BooleanField(db_index=True, default=False)),
                ("app", models.CharField(max_length=20)),
                ("key", models.CharField(max_length=255)),
                ("value", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("config", models.JSONField(blank=True, default=dict, null=True)),
            ],
            options={
                "ordering": ["-id"],
                "unique_together": {("app", "key")},
            },
        ),
    ]
